import DataFrames: DataFrame, AbstractDataFrame, metadata!, metadata, nrow
import Sobol: SobolSeq, next!
import Random: AbstractRNG, default_rng

## The design helpers below follow R `pomp`'s `slice_design`,
## `profile_design`, `runif_design`, and `sobol_design`, returning
## `DataFrame`s with the same column layout.

"""
    slice_design(center; slices...)

Construct a design for a likelihood slice, matching R `pomp`'s
`slice_design`. `center` is a `NamedTuple` of parameters. Each keyword
argument names a parameter of `center` and gives the vector of values
it takes along its slice; every other parameter is held at its value
in `center`. The result is a `DataFrame` with one column per parameter
of `center` and a `slice` column holding the name of the parameter
varied in that row. The rows of all slices are stacked in the order
given.

# Example
```julia
slice_design((a=1.5,k=7.0,x0=5.0); a=1.0:0.1:2.0, k=[3.0,5.0,7.0,9.0])
```
"""
slice_design(center::NamedTuple; slices...) = begin
    isempty(slices) && error("`slice_design`: at least one slice must be given.")
    pnames = keys(center)
    all(v -> v isa Real, values(center)) ||
        error("`slice_design`: `center` must be a `NamedTuple` of real numbers.")
    :slice ∈ pnames &&
        error("`slice_design`: a parameter cannot be named `slice`.")
    frames = map(collect(pairs(slices))) do (nm,vals)
        nm ∈ pnames ||
            error("`slice_design`: variable `$nm` does not appear in `center`.")
        v = vals isa Real ? [Float64(vals)] : collect(Float64,vals)
        n = length(v)
        df = DataFrame([p => fill(Float64(getfield(center,p)),n) for p ∈ pnames]...)
        df[!,nm] = v
        df[!,:slice] = fill(nm,n)
        df
    end
    reduce(vcat,frames)
end

check_bounds(lower::NamedTuple, upper::NamedTuple) = begin
    ln = keys(lower)
    Set(ln) == Set(keys(upper)) ||
        error("names of `lower` and `upper` must match.")
    isempty(ln) && error("`lower` and `upper` must name at least one variable.")
    for k ∈ ln
        (lower[k] isa Real && upper[k] isa Real) ||
            error("`lower` and `upper` must be `NamedTuple`s of real numbers.")
        upper[k] ≥ lower[k] ||
            error("upper values should be at least as large as lower ones (variable `$k`).")
    end
    ln
end

"""
    runif_design(lower, upper, nseq; rng = Random.default_rng())

`nseq` points drawn uniformly and independently from the box with
corners `lower` and `upper` (`NamedTuple`s with matching names),
returned as a `DataFrame` with one column per variable, in the order of
`lower`. Matches R `pomp`'s `runif_design`.
"""
runif_design(
    lower::NamedTuple,
    upper::NamedTuple,
    nseq::Integer;
    rng::AbstractRNG = default_rng(),
) = begin
    nseq ≥ 0 || error("`nseq` < 0.")
    ln = check_bounds(lower,upper)
    DataFrame(
        [k => Float64(lower[k]) .+ (Float64(upper[k])-Float64(lower[k])).*rand(rng,nseq)
         for k ∈ ln]...
    )
end

"""
    sobol_design(lower, upper, nseq)

`nseq` points of a Sobol' low-discrepancy sequence spanning the box
with corners `lower` and `upper` (`NamedTuple`s with matching names),
returned as a `DataFrame` with one column per variable, in the order of
`lower`. Matches R `pomp`'s `sobol_design` in purpose; the sequence is
generated by `Sobol.jl`, so the individual points differ from those R
produces. The result is deterministic.
"""
sobol_design(
    lower::NamedTuple,
    upper::NamedTuple,
    nseq::Integer,
) = begin
    nseq ≥ 0 || error("`nseq` < 0.")
    ln = check_bounds(lower,upper)
    d = length(ln)
    s = SobolSeq(d)
    x = zeros(Float64,d)
    m = Matrix{Float64}(undef,nseq,d)
    for i ∈ 1:nseq
        next!(s,x)
        m[i,:] .= x
    end
    DataFrame(
        [ln[j] => Float64(lower[ln[j]]) .+ (Float64(upper[ln[j]])-Float64(lower[ln[j]])).*m[:,j]
         for j ∈ 1:d]...
    )
end

"""
    profile_design(; lower, upper, nprof, type = :runif, rng, profiled...)

Construct a design for a profile likelihood computation, matching R
`pomp`'s `profile_design`. Each keyword argument in `profiled...` names
a parameter to profile over and gives the vector of values it takes.
The full grid over the profiled parameters is formed (the first
argument varying fastest), and for every grid point `nprof` starting
values of the remaining parameters are drawn from the box with corners
`lower` and `upper` (`NamedTuple`s with matching names), uniformly at
random (`type = :runif`, using `rng`) or from a Sobol' sequence
(`type = :sobol`).

The result is a `DataFrame` with the profiled columns first, followed
by the columns of `lower`; each grid point occupies `nprof` consecutive
rows. The names of the profiled parameters are recorded in the
data frame's metadata under the key `"profiled"`, which
[`profile`](@ref) uses to check that they are not perturbed.
"""
profile_design(;
    lower::NamedTuple,
    upper::NamedTuple,
    nprof::Integer,
    type::Symbol = :runif,
    rng::AbstractRNG = default_rng(),
    profiled...,
) = begin
    isempty(profiled) &&
        error("`profile_design`: at least one variable to profile over must be given.")
    nprof > 0 || error("`profile_design`: `nprof` must be positive.")
    type ∈ (:runif,:sobol) ||
        error("`profile_design`: `type` must be `:runif` or `:sobol`.")
    pv = collect(pairs(profiled))
    pnames = first.(pv)
    for k ∈ pnames
        k ∈ keys(lower) &&
            error("`profile_design`: profiled variable `$k` must not appear in `lower`/`upper`.")
    end
    grids = [v isa Real ? [Float64(v)] : collect(Float64,v) for (_,v) ∈ pv]
    rows = vec(collect(Iterators.product(map(eachindex,grids)...)))
    n = length(rows)
    x = DataFrame(
        [pnames[j] => [grids[j][r[j]] for r ∈ rows] for j ∈ eachindex(pnames)]...
    )
    y = if type == :runif
        runif_design(lower,upper,n*nprof;rng)
    else
        sobol_design(lower,upper,n*nprof)
    end
    out = hcat(repeat(x,inner=nprof),y)
    metadata!(out,"profiled",collect(pnames),style=:note)
    out
end
